export const albums = [{
    album_id: 1,
    title: "Moderne Plastik",
    items: [{
        id: 'pCSLggvdsi8vvvb3lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'baker without direction',
        subtext: 'A subtext',
        description: 'Collaboration',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    }, {
        id: 'pCSLggvdsi8b3lllzR4gfTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'girl of yesterday',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    }, {
        id: 'pCSLggvdsi8b3123lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'bandits of nightmares',
        subtext: 'A subtext',
        description: 'Article',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/tech',
    }, {
        id: 'pCSLggvdsi8b3l323llzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'traitors of the sea',
        subtext: 'A subtext',
        description: 'Scientific Paper',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/animals',
    }, {
        id: 'pCSLggvdsi8b3lllzRTfgsdfgggggLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'officers and descendants',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    }, {
        id: 'pCSLggvds3222i8b3lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'humans and rebels',
        subtext: 'Difference is the key',
        description: 'Performance & Art',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/tech',
    }, {
        id: 'pCSLggvdsi8b3lllz444RTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'sword of the stockades',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    }, {
        id: 'pCSLggvdsi8b3lllz777RTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'origin of freedom',
        subtext: 'A subtext',
        description: 'Workshop',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    }, {
        id: 'pCSLggvdsi8b0003lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'escape the demons',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/animals',
    },]
}, {

    album_id: 2,
    title: "Impressionismus",
    items: [{
        id: 'pCSLggvdsi8b3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'spy of the solstice',
        subtext: 'A different long subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    }],

}, {
    album_id: 3,
    title: "Aquarell im späten 18. Jahrhundert",
    items: [{
        id: 'pCSLggvdsiasdf8b3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'lords without a conscience',
        subtext: 'Lets find it out and look deeper',
        description: 'Bachelor',
        imageUrl: 'https://placeimg.com/460/341/animal',
    }, {
        id: 'pCSLggvdsi8b3fffzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'women of despair',
        subtext: 'Mysterious',
        text: ['Random text 1', 'Random text 2'],
        imageUrl: 'https://placeimg.com/640/480/any'
    }],
}, {
        album_id: 4,
        title: "Digitale Kunst",
        items: [{
            id: 'pCSLggvdsiasdf8b3zRTLM4dJR',
            date_created: '2020-04-27T11:01:37.246606Z',
            title: 'lords without a conscience',
            subtext: 'Lets find it out and look deeper',
            description: 'Bachelor',
            imageUrl: 'https://placeimg.com/460/341/animal',
        }, {
            id: 'pCSLggvdsi8b3fffzRTLM4dJR',
            date_created: '2020-04-27T11:01:37.246606Z',
            title: 'women of despair',
            subtext: 'Mysterious',
            text: ['Random text 1', 'Random text 2'],
            imageUrl: 'https://placeimg.com/640/480/any'
        }],
}]