export const entriesList = [
    {
        id: 'pCSLggvdsi8vvvb3lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'An extra extra long title',
        subtext: 'A subtext',
        description: 'Collaboration',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    },
    {
        id: 'pCSLggvdsi8b3lllzR4gfTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 2',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    },
    {
        id: 'pCSLggvdsi8b3123lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 1',
        subtext: 'A subtext',
        description: 'Article',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/tech',
    },
    {
        id: 'pCSLggvdsi8b3l323llzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 2',
        subtext: 'A subtext',
        description: 'Scientific Paper',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/animals',
    },
    {
        id: 'pCSLggvdsi8b3lllzRTfgsdfgggggLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 3',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    },
    {
        id: 'pCSLggvds3222i8b3lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 4',
        subtext: 'Difference is the key',
        description: 'Performance & Art',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/tech',
    },
    {
        id: 'pCSLggvdsi8b3lllz444RTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 5',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    },
    {
        id: 'pCSLggvdsi8b3lllz777RTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 6',
        subtext: 'A subtext',
        description: 'Workshop',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    },
    {
        id: 'pCSLggvdsi8b0003lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 7',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/animals',
    },
    {
        id: 'pCSLggvdsi8b3lllz789RTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 8',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    },
    {
        id: 'pCSLggvdsirtz8b3lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 9',
        subtext: 'A subtext',
        description: 'Mission',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/nature',
    },
    {
        id: 'pCSLggvdsi8b3l456llzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 10',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    },
    {
        id: 'pCSLggvdsi8b3lllzRT456LM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 11',
        subtext: 'A subtext',
        description: 'Conference',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/tech',
    },
    {
        id: 'pCSLgg234vdsi8b3lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 12',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    },
    {
        id: 'pCSLggvdsi8b3lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 13',
        subtext: 'A subtext',
        description: 'Exhibition',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/nature',
    },
    {
        id: 'pCSLggvdsi8b3zRdddTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 14',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/animals',
    },
    {
        id: 'pCSLggvdsi8bbbb3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 15',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    },
    {
        id: 'pCSLggvdsi8oiouiob3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 16',
        subtext: 'A subtext',
        description: 'Exhibition',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    },
    {
        id: 'pCSLggasdfvdsi8b3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 17',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/tech',
    },
    {
        id: 'pCSLggvdsi8asdb3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 18',
        subtext: 'A subtext',
        description: 'Master Work',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/nature',
    },
    {
        id: 'pCSLggvdsi8ffsdb3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 19',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/animals',
    },
    {
        id: 'pCSLggvdsi8b3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Title 29',
        subtext: 'A different long subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    },
    {
        id: 'pCSLggvdsiasdf8b3zRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'Unknown',
        subtext: 'Lets find it out and look deeper',
        description: 'Bachelor',
        imageUrl: 'https://placeimg.com/460/341/animal',
    },
    {
        id: 'pCSLggvdsi8b3fffzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'TBD',
        subtext: 'Misterious',
        text: ['Random text 1', 'Random text 2'],
    },
]