export const entriesList = [
    {
        id: 'pCSLggvdsi8vvvb3lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'baker without direction',
        subtext: 'A subtext',
        description: 'Collaboration',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    },
    {
        id: 'pCSLggvdsi8b3lllzR4gfTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'girl of yesterday',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/people',
    },
    {
        id: 'pCSLggvdsi8b3123lllzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'bandits of nightmares',
        subtext: 'A subtext',
        description: 'Article',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/tech',
    },
    {
        id: 'pCSLggvdsi8b3l323llzRTLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'traitors of the sea',
        subtext: 'A subtext',
        description: 'Scientific Paper',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/animals',
    },
    {
        id: 'pCSLggvdsi8b3lllzRTfgsdfgggggLM4dJR',
        date_created: '2020-04-27T11:01:37.246606Z',
        title: 'officers and descendants',
        subtext: 'A subtext',
        description: 'Performance',
        source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
        imageUrl: 'https://placeimg.com/460/341/arch',
    },
    {
     id: 'pCSLggvds3222i8b3lllzRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'humans and rebels',
     subtext: 'Difference is the key',
     description: 'Performance & Art',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/tech',
 },
 {
     id: 'pCSLggvdsi8b3lllz444RTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'sword of the stockades',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/arch',
 },
 {
     id: 'pCSLggvdsi8b3lllz777RTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'origin of freedom',
     subtext: 'A subtext',
     description: 'Workshop',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/people',
 },
 {
     id: 'pCSLggvdsi8b0003lllzRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'escape the demons',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/animals',
 },
 {
     id: 'pCSLggvdsi8b3lllz789RTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'losing a storm',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/arch',
 },
 {
     id: 'pCSLggvdsirtz8b3lllzRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'mouse of the light',
     subtext: 'A subtext',
     description: 'Mission',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/nature',
 },
 {
     id: 'pCSLggvdsi8b3l456llzRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'snake of the void',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/arch',
 },
 {
     id: 'pCSLggvdsi8b3lllzRT456LM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'hunters of the world',
     subtext: 'A subtext',
     description: 'Conference',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/tech',
 },
 {
     id: 'pCSLgg234vdsi8b3lllzRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'snakes of my imagination',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/people',
 },
 {
     id: 'pCSLggvdsi8b3lllzRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'slaves and horses',
     subtext: 'A subtext',
     description: 'Exhibition',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/nature',
 },
 {
     id: 'pCSLggvdsi8b3zRdddTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'foes and girls',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/animals',
 },
 {
     id: 'pCSLggvdsi8bbbb3zRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'unity without a goal',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/people',
 },
 {
     id: 'pCSLggvdsi8oiouiob3zRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'choice of dread',
     subtext: 'A subtext',
     description: 'Exhibition',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/arch',
 },
 {
     id: 'pCSLggasdfvdsi8b3zRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'battle of the slaves',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/tech',
 },
 {
     id: 'pCSLggvdsi8asdb3zRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'forsaking my wife',
     subtext: 'A subtext',
     description: 'Master Work',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/nature',
 },
 {
     id: 'pCSLggvdsi8ffsdb3zRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'assassin of the ocean',
     subtext: 'A subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/animals',
 },
 {
     id: 'pCSLggvdsi8b3zRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'spy of the solstice',
     subtext: 'A different long subtext',
     description: 'Performance',
     source: 'http://base.uni-ak.ac.at/portfolio/taxonomy/album',
     imageUrl: 'https://placeimg.com/460/341/people',
 },
 {
     id: 'pCSLggvdsiasdf8b3zRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'lords without a conscience',
     subtext: 'Lets find it out and look deeper',
     description: 'Bachelor',
     imageUrl: 'https://placeimg.com/460/341/animal',
 },
 {
     id: 'pCSLggvdsi8b3fffzRTLM4dJR',
     date_created: '2020-04-27T11:01:37.246606Z',
     title: 'women of despair',
     subtext: 'Mysterious',
     text: ['Random text 1', 'Random text 2'],
     imageUrl: 'https://placeimg.com/640/480/any'
 },
]